agents:
  agent_template:
    description: Template/example agent for creating new specialized agents
    features:
      basic_processing: true
      template_operations: true
    host: localhost
    module_path: agent_template
    name: Agent Template
    port: 10100
    resources:
      max_cpu_percent: 25
      max_memory_mb: 256
    timeouts:
      health_check: 10
      startup: 30
      task_execution: 60
  orchestrator:
    description: Central coordinator for all agent communication
    features:
      health_monitoring: true
      mcp_client: true
      task_routing: true
    host: localhost
    module_path: orchestrator_agent
    name: Orchestrator Agent
    port: 10005
    resources:
      max_cpu_percent: 50
      max_memory_mb: 512
    timeouts:
      health_check: 10
      startup: 30
      task_execution: 300

database:
  connection:
    database: framework_system
    host: localhost
    password: framework_password
    port: 5432
    username: framework_user
  enabled: false
  pool:
    connection_timeout: 30
    max_connections: 10
    min_connections: 1
  type: sqlite
deployment:
  docker:
    base_image: python:3.11-slim
    exposed_ports:
    - 10005
    - 10100
    - 11000
    requirements_file: requirements.txt
  kubernetes:
    namespace: framework-system
    replicas: 1
    resource_limits:
      cpu: 500m
      memory: 1Gi
    resource_requests:
      cpu: 100m
      memory: 256Mi
  strategy: standalone
development:
  debug_mode: true
  hot_reload: true
  mock_external_services: false
  test_configuration:
    performance_benchmarks: false
    run_integration_tests: true
    test_data_cleanup: true
  test_data_generation: true
features:
  advanced_security: true
  cloud_deployment: false
  experimental_analysis: false
  multi_tenant_support: false
  performance_optimization: true
integrations:
  google_api:
    api_key: ${GOOGLE_API_KEY}
    enabled: true
    timeout_seconds: 30
  openai_api:
    api_key: ${OPENAI_API_KEY}
    enabled: false
    model: gpt-4
logging:
  backup_count: 5
  console_output: true
  file: logs/framework.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size_mb: 100
mcp_server:
  features:
    health_checks: true
    metrics_collection: true
    security_monitoring: true
    trace_logging: true
  host: localhost
  max_connections: 100
  paths:
    execute: /execute
    health: /health
    security_status: /security/status
    tools: /tools
  port: 11000
  timeout_seconds: 30
  workers: 1
monitoring:
  alerts:
    email_recipients: []
    enabled: false
    slack_webhook: ''
    thresholds:
      cpu_percent: 80
      error_rate_percent: 5
      memory_percent: 85
      response_time_ms: 1000
  enabled: true
  health_checks:
    failure_threshold: 3
    interval_seconds: 15
    timeout_seconds: 5
  metrics:
    collection_interval_seconds: 30
    export_enabled: true
    export_interval_hours: 6
    retention_hours: 24
production:
  development:
    debug_mode: false
    hot_reload: false
  logging:
    console_output: false
    level: WARNING
  mcp_server:
    max_connections: 500
    workers: 4
  monitoring:
    alerts:
      enabled: true
  security:
    api_keys:
      mcp_server: ${MCP_API_KEY}
    rate_limiting:
      auth_requests_per_minute: 50
      requests_per_minute: 1000
security:
  api_keys:
    default_expiry_hours: 24
    mcp_server: mcp-dev-key
  authentication:
    failed_attempts_threshold: 5
    lockout_duration_minutes: 60
    require_api_key: true
    timing_attack_protection: true
  cors:
    allowed_headers:
    - Content-Type
    - Authorization
    - X-API-Key
    allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allowed_origins:
    - http://localhost:*
    - http://127.0.0.1:*
    enabled: true
  headers:
    content_security_policy: default-src 'self'
    hsts_max_age: 31536000
    x_content_type_options: nosniff
    x_frame_options: DENY
  rate_limiting:
    auth_requests_per_minute: 10
    burst_allowance: 20
    enabled: true
    requests_per_minute: 100
system:
  environment: development
  name: Multi-Agent Framework
  version: 2.0.0
